### PR TITLE
update: prevent rewriting and reduce bytes

### PR DESCRIPTION
**Pull request by a13821190779**

### CODE REVIEW

**Comment by Imperat** [comment]
Who of us is familiar with eslint? It's needed to disable no-void rule in this line)

**Comment by iamkun** [comment]
sad story from eslint 

> Expected 'undefined' and instead saw 'void'  no-void

**Comment by a13821190779** [comment]
Vscode does not prompt...

**Comment by iamkun** [comment]
Add this above at the end of the line could solve this:
```
// eslint-disable-line no-void
```

**Comment by a13821190779** [comment]
i repr

**Pull request closed without merging**
