### PR TITLE
Add fil locale (same as tl-ph)

### PR DESCRIPTION
**Pull request by aadityataparia**
Filipino language (`fil`) is synonym to tagalog language (`tl-ph`)

https://en.wikipedia.org/wiki/Filipino_language#Filipino_vs._Tagalog

### CODE REVIEW

**Comment by iamkun** [comment]
Thanks. 

One more question, what's the difference between Philippine languages (phi), fil and tl-ph, and what's tl-ph stand for (is it two combined language)

**Comment by aadityataparia** [comment]
They are basically same, and `tl-ph` is Tagalog (Philippines), `tl` alias can also be added if we want that too. They are just different ISOs, `tl` -> two letter language code, `tl-ph` langauge + country, `fil` -> three letter language code. 

I wanted to add `fil` because I am using it in i18n.

Screen Shot 2019-05-13 at 12 17 19

**Comment by iamkun** [comment]
As mentioned in #171, we use https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes as a reference. 
We use tl-ph to keep the same with moment.js, surprisingly, it's not listed on that table (but fil does)

**Comment by aadityataparia** [comment]
> As mentioned in #171, we use https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes as a reference.
We use tl-ph to keep the same with moment.js, surprisingly, it's not listed on that table (but fil does)

Rename `tl-ph` to `tl` maybe. Or create alias to keep compatible with moment.

**Comment by iamkun** [comment]
Found two related issue / pr in moment.js 

https://github.com/moment/moment/issues/3054

https://github.com/moment/moment/pull/4239

**Comment by aadityataparia** [comment]
Tried this today, even this works 
```js
dayjs.locale('fil', dayjs.Ls['tl-ph'])
```

**Pull request closed without merging**
