### PR TITLE
add a plugin named "preciseDiff" and its test code for "dayjs"

### PR DESCRIPTION
**Pull request by huangjinlin**
this is how about it:https://github.com/huangjinlin/dayjs-precise-range

### CODE REVIEW

**Comment by huangjinlin** [comment]
`
var dayjs = require('dayjs');
var preciseDiff = require('dayjs/plugin/preciseDiff')
dayjs.extend(preciseDiff);
var m1 = dayjs('2014-01-01 12:00:00');
var m2 = dayjs('2014-02-03 15:04:05');
var diff = dayjs.preciseDiff(m1, m2); // '1 month 2 days 3 hours 4 minutes 5 seconds'
`

**Comment by iamkun** [comment]
CI failed. Please run `npm run lint` before open a pull request. Thanks.

**Comment by huangjinlin** [comment]
@iamkun i have modify through eslint

**Comment by iamkun** [comment]
@huangjinlin Cool thanks. I'm waiting for others opinions before merging. Please be patient.

**Comment by bas080** [comment]
I would expect extensions to be an opt-in thing. I am more for a separate library approach.

The code/tests you have written look great. You might not want maintenance responsibility, or you would like it to be part of the dayjs ecosystem. Maybe @iamkun can start an organization and create separate repositories for these libraries that build on dayjs. If that is the case, you would need to document and point to the libraries in the dayjs docs, similar to what moment.js docs do.

**Comment by iamkun** [comment]
@huangjinlin Thanks for your code.

Still, I tend to agree not to merge this into our main code base.

Instead, you may could publish your plugin by yourself. 

And I'll consider @bas080 's words, and still, a lot work to do. 😬

**Comment by cloydlau** [comment]
That preciseDiff plugin is under ISC license...

**Pull request closed without merging**
