### PR TITLE
Typo fix in API-reference.md

### PR DESCRIPTION
**Pull request by ledleds**
Just noticed this tiny typo in your docs!

### CODE REVIEW

**Comment by xxyuk** [comment]
@ledleds I think we should do a global search / replace of other language such as `es-es` and `pt-br`

**Comment by ledleds** [comment]
> @ledleds I think we should do a global search / replace of other language such as `es-es` and `pt-br`

Good shout, will do it now

**Comment by iamkun** [comment]
Thanks

**Pull request merged**
