### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by wangyiz4262**
Use Prettier to format source files

### CODE REVIEW

**Comment by iamkun** [comment]
Thanks, but I'm not sure if this is a must do change, since the format rules of prettier has a little different with es-lint in .js files. But markdown format looks great.

**Comment by iamkun** [comment]
@wangyiz4262  one more thing, it would be great if you could make a new PR with only prettier added to the project as well as the pre-commit lint or something alike, and we could do prettier during our CI running. A PR 104 files change make it impossible to review.

**Comment by wangyiz4262** [comment]
@iamkun Very happy to. I will get that done tomorrow. Actually it is not necessary to make a new PR. I can force push the changes so that this PR will be updated accordingly.

**Comment by iamkun** [comment]
@wangyiz4262 that would be nice,  take your time please.

**Comment by wangyiz4262** [comment]
Hi @iamkun, I added Prettier into CI but disabled pre-commit because it wouldn't let me commit without updating all the files. Therefore I need you to approve the PR first, and then I will create another PR to re-enable eslint in the pre-commit hook.

**Comment by wangyiz4262** [comment]
@iamkun I just realized this won't work because just adding Prettier to CI will only prettify files on the flight. The real source files still don't change. There has to be a big change contain all the prettified files.

**Comment by iamkun** [comment]
How about we just start from `.md` files. Simply add prettier and a npm script, and that's enough. After that we could consider this should be added to precommit or ci or something else.

**Comment by wangyiz4262** [comment]
@iamkun I added Prettier configuration without hook up to eslint, and also formatted all the markdown files in a separate commit.

**Comment by iamkun** [comment]
Looks good, but better revert the last commit and leave the only change with add prettier. There's no need to review diffs made by prettier.

**Comment by wangyiz4262** [comment]
@iamkun Got you. I have reverted the last commit. The source files can be prettified at any time later.

**Pull request merged**
