### PR TITLE
Croatian translation

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by iamkun** [comment]
@diomed Thanks, but CI failed. run `npm run lint` before PR.

> 7:1  error  Expected indentation of 2 spaces but found 4  indent

**Comment by diomed** [comment]
can you please fix it and merge? I'm a translator, not a coder

**Comment by iamkun** [comment]
@diomed All right, I'll do it. Thanks again for your translation. It's a great help.

**Pull request merged**
