### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
This adds a badge to the `README.md` that displays the npm install size

### CODE REVIEW

**Comment by styfle** [comment]
Should I add this badge to the `README.zh-CN.md` file too?

**Comment by iamkun** [comment]
THX, but not sure if we really need this badge or not? In my mind, what our user concerned most is the bundle size (dayjs.min.js), not install size (whole project with docs, test, ...).

**Comment by styfle** [comment]
Sure it's not as important as the bundle size but it will let users know that you are not publishing large asset files or including large dependencies that are unnecessary.

For example, [jQuery@3.3.0](https://packagephobia.now.sh/result?p=jquery@3.3.0) accidentally published dependencies that were not necessary which lead to a 15 MB install size.

**Comment by iamkun** [comment]
Great, i know you mean. Let's just pending this and listen to others opinions.

Plus, TypeScript enthusiast,  could you please help me check this issue #139 related to TS typings. I'm not good with this.

**Comment by styfle** [comment]
I fixed the TS typings bug.

Also I updated the `README.zh-CN.md` too 👍

**Comment by styfle** [comment]
@iamkun Anything else you need for this to get merged?

**Comment by iamkun** [comment]
Nothing. Just waiting for other's review or discussion. Pending.

**Comment by styfle** [comment]
I just rebased on master, build is passing again

**Comment by iamkun** [comment]
@styfle  Thanks. I'm not going to merge this PR at the moment. We have a `.npmignore` file and should be fine. Still, discussion welcome.

**Comment by styfle** [comment]
@iamkun I'm not sure I understand.
What does `.npmignore` file have to do this the `README.md` file?

**Comment by iamkun** [comment]
Agreed. But just don't think it necessary.

**Comment by hustcc** [comment]
So many badges now.

I think there is no need to show install size, but can pr for reduce the install size.

bundle size is the feature of this project, but install size not.

**Comment by iamkun** [comment]
@hustcc Agreed!

**Comment by iamkun** [comment]
Final decision. We don't need this at the moment.

**Pull request closed without merging**
