### PR TITLE
translate updated docs in Korean

### PR DESCRIPTION
**Pull request by jiyeonseo**
as titled. 

- fix typo. 
- translate updated docs 

It would be great to review from @ujuc who is the origin contributor for this translation if possible! :) 

#171

### CODE REVIEW

**Comment by ujuc** [comment]
Thanks @jiyeonseo  👍 ~~~!!!

**Comment by jiyeonseo** [comment]
@iamkun Could you approve this pr? 😃

**Comment by iamkun** [comment]
great

**Pull request merged**
