### PR TITLE
fix: hotfix for `Duration` types

### LINKED ISSUE #1354: 1.10.4 broke duration creation type in typescript
**Describe the bug**
In your own documentation: https://day.js.org/docs/en/durations/add
```typescript
var a = dayjs.duration(1, 'd');
var b = dayjs.duration(2, 'd');

a.add(b).days(); // 3
```
it shows:
```
No overload matches this call.
  Overload 1 of 3, '(units: Partial<{ milliseconds: number; seconds: number; minutes: number; hours: number; days: number; months: number; years: number; weeks: number; }>): Duration', gave the following error.
    Argument of type 'Duration' is not assignable to parameter of type 'Partial<{ milliseconds: number; seconds: number; minutes: number; hours: number; days: number; months: number; years: number; weeks: number; }>'.
      Types of property 'milliseconds' are incompatible.
        Type '() => number' is not assignable to type 'number'.
  Overload 2 of 3, '(time: number, unit?: DurationUnitType | undefined): Duration', gave the following error.
    Argument of type 'Duration' is not assignable to parameter of type 'number'.
  Overload 3 of 3, '(ISO_8601: string): Duration', gave the following error.
    Argument of type 'Duration' is not assignable to parameter of type 'string'.ts(2769)
```

**Expected behavior**
No typescript type mismatch failure

**Information**
 - Day.js Version [e.g. v1.10.4]
 - OS: [windows]
 - Browser node 14.15.0
 - Time zone: not applicable

### PR DESCRIPTION
**Pull request by zardoy**
closes #1354

### CODE REVIEW

**Comment by iamkun** [comment]
Thanks, would you please rebase the dev branch, cause I have just fixed the unit test error.

**Comment by zardoy** [comment]
@iamkun No worries, I didn't touch files that you have changed so there is no conflicts with your branch

**Comment by iamkun** [comment]
But the unit test in this PR failed.

image

**Comment by zardoy** [comment]
fixed. Sorry for the response time

**Comment by iamkun** [comment]
Thanks

**Pull request merged**
