### PR TITLE
fix: move en ordinal function to locale file

### PR DESCRIPTION
**Pull request by asvny**
Fix for #1482

### CODE REVIEW

**Comment by iamkun** [comment]
This will make the core bundle size larger.

What I suggest to do is not to import local from en.js to main/index.js

**Comment by asvny** [comment]
Interesting ... how these changes make core bundle larger ? one is locale and other is a plugin. 

`What I suggest to do is not to import local from en.js to main/index.js`

Not a good idea I reckon .. what if I use other features of en locale.

**Comment by iamkun** [comment]
At present, the en's `ordinal` function is inside the plugin file, not the main bundle.

**Comment by asvny** [comment]
Yeah .. wouldn't it make sense to have in locale file ? locale code inside a non closely related plugin feels weird.

How about in both the files ? might not break the app I guess

**Comment by iamkun** [comment]
Yes, I'd like to have a full-size en locale file, but not imported to the main bundle.

**Pull request closed without merging**
