### PR TITLE
Add `Do` date format logic

### PR DESCRIPTION
**Pull request by iYanovoy**
Add `Do` date format logic

### CODE REVIEW

**Comment by Pareder** [comment]
What if user changes locale and it is not `en`?

Also I would recommend to cover this format with tests.

You can add `do` and `DDDo` formats as well.

**Comment by iYanovoy** [comment]
Ok, I will think about it. But also have a question, Is plugins
`isSameOrBefore` and `isSameOrAfter` work properly, for now? Because it
brokes our validations.

пн, 4 вер. 2023 р. о 09:50 Anton Cherniavskyi ***@***.***>
пише:

**Comment by iamkun** [comment]
https://github.com/iamkun/dayjs/issues/2434#issuecomment-1702845542

**Comment by Atulkumar112** [comment]
> Add `Do` date format logic

Hi @iYanovoy 

i am using 'Do' but it's given me the wrong value.
```
.format(`dddd, DD Do MMMM YYYY`)   
```
and o/p is Friday, 08 8o December 2023 and it should be Friday, 08th December 2023

please have a look on this.

**Pull request closed without merging**
