### PR TITLE
fix: update fa locale

### PR DESCRIPTION
**Pull request by Soheil-Saberi**
update translate month ,monthsShort , weekdaysShort and relativeTime.past

### CODE REVIEW

**Comment by iamkun** [comment]
we use https://github.com/moment/moment/blob/develop/src/locale/fa.js as a reference, can you please tell us why such a difference between the two?

**Comment by Soheil-Saberi** [comment]
Hi iamkun

Firstly, thank you for paying attention to this issue and emphasizing the
importance of accurate translations based on location.

The common calendar of Persian speakers and people of Iran is the Jalali
calendar.

The order of the months of the Jalali calendar is as follows :


No

Month (Persian Language)

Month (English Language)

1

فروردین

Farvardin

2

اردیبهشت

Ordibehesht

3

خرداد

Khordad

4

تیر

Tir

5

مرداد

Mordad

6

شهریور

Shahrivar

7

مهر

Mehr

8

آبان

Aban

9

آذر

Azar

10

دی

Dey

11

بهمن

Bahman

12

اسفند

Esfand

Click here for more details
<https://en.wikipedia.org/wiki/Iranian_calendars>

Most libraries and frameworks use the dayjs library (for example, in
the DatePicker
of the Mantain library <https://mantine.dev/dates/date-picker/>).

Because of this problem, programmers were forced to develop side libraries
from the dayjs library (for example, dayjs-jalali
<https://github.com/torbatian/dayjs-jalali> , jalaliday
<https://github.com/alibaba-aero/jalaliday>) ,moment.js library has exactly
the same problem (Persian example : moment-jalaali
<https://github.com/jalaali/moment-jalaali>).
For these reasons, I requested to change the Farsi translation

**Comment by iamkun** [comment]
Thanks for the details above.

I'm afraid I can't decide whether to merge this or not since it has a lot of differences from the original moment's locale.

I'll label this pr and wait for more reviews from your native speakers.

**Comment by Soheil-Saberi** [comment]
Thank you for paying attention to this issue
Additionally, I share this issue with Farsi language developers to contribute to its improvement

**Comment by cnaez** [comment]
I am agree with Soheil.
We need some changes to make dayjs better for Iranian developers.
Thank you guys

**Comment by emadecode** [comment]
Dear @iamkun
The translation of the month names in this pull request is correct to my knowledge as a native speaker.

**Comment by MahdiMhqq** [comment]
@iamkun 
Hi dear kun,
As a native persian speaker, i can approve soheil's changes. Please merge this pull req.

**Comment by iamkun** [comment]
Cheers

**Comment by raminjafary** [comment]
@iamkun @Soheil-Saberi This PR is getting it wrong by simply translating locale months to **Solar Hijri** calendar but not taking care of all the quirks of date and time transformations. Dayjs' locale provides literal translations of the Gregory calendar which is correct. I believe this PR should be reverted to avoid users confusions and misunderstanding.

I suggest to use this plugin for Persian users:
https://github.com/alibaba-aero/jalaliday

**Comment by raminjafary** [comment]
Most of the countries do not have solar calendar. As a result, they have one to one mapping of English translations for the months. But If you use solar months you have to use solar calendar date-time, too.

**Comment by raminjafary** [comment]
There is no guarantee that the other locale files of the other countries in Dayjs repo is being approved context wise.
Dayjs is neither a solar nor lunar system based calendar so it doesn't make sense to provide translations of any other calendar as is without necessary date time modifications. 
For example, As of my experience, January which is يناير in ar-IQ locale is just a Gregorian equivalent with the same date time system. Although the first day of the week is different, it is configurable via Dayjs locale plugin.

**Comment by mokhosh** [comment]
What an irresponsible PR!
This change is based on a wrong plugin architecture where the OP doesn't try to handle generation of month names in the plugin, rather he changes the original month names regardless of what calendar system dayjs is using.

This needs to be reverted asap.

Related: https://github.com/alibaba-aero/jalaliday/issues/39

**Comment by raminjafary** [comment]
@iamkun

**Comment by raminjafary** [comment]
I opened a PR to undo these changes. @mokhosh @amirhmoradi It would be great if I could have your comments or confirmations on this PR #2411.

**Pull request merged**
