### PR TITLE
nonstandard ISO 8601 format string supported

### PR DESCRIPTION
**Pull request by guisturdy**
Bugfix #254 

add support 

- 2018-06-26 01:02
- 2018-06-26 01
- 2018-06-26 01:02Z
- 2018-06-26 01Z
- 2018-06-26 1:2
- 2018-06-26 1:2Z
- 2018-06-26 1
- 2018-06-26 1Z

diffrent with moment
```
  moment('2018') => 2018-01-01T08:00:00+08:00
  dayjs('2018')  => 2018-01-01T00:00:00+08:00
  moment('2018-01-01 1') => Invalid Date
  dayjs('2018-01-01 1')  => 2018-01-01 01:00:00
```

### CODE REVIEW

**Comment by iamkun** [comment]
@guisturdy Thank for the code. However, while parsing '2018-12-31T10:59:09+08:00', it fails.

PS: `new Date('2018-12-31T10:59:09+08:00')` is OK.

**Comment by iamkun** [comment]
Besides, one question here, what's the advantage of using `Date('2018-01-02 03:04:05.123Z')`, instead of `Date(2018, 0 , 2, 3 ....)`

**Comment by guisturdy** [comment]
@iamkun fix the bug of parsing '2018-12-31T10:59:09+08:00

因为如果想修复 #254 的问题，我们就需要把`年月日时分秒毫秒和timezone`都取出来，未指定则分配默认值。而`new Date(year, monthIndex [, day [, hours [, minutes [, seconds [, milliseconds]]]]])`不能指定时区，所以我考虑使用拼凑一个ISO字符串的方法来构造Date实例

**Comment by loveonelong** [comment]
When can I use it, I am troubled by these bugs...

**Comment by iamkun** [comment]
I'll close this PR since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
