### PR TITLE
Add Japanese documents

### PR DESCRIPTION
**Pull request by ohbarye**
Hello @iamkun 
As I promised on https://github.com/iamkun/dayjs/issues/164, I translated all documents into Japanese.

I hope those docs would help more people. 

Closes: #164

### CODE REVIEW

**Comment by iamkun** [comment]
Great work thanks.

**Comment by ohbarye** [comment]
@iamkun 
My pleasure.

BTW, should I move `README.ja.md` which this PR adds to `docs/ja/README-ja.md` in this PR? Or, should such structure change happen after this gets merged?


```
.
├── docs
│   └── ja
│        ├── API-reference.md
│        ├── I18n.md
│        ├── Installation.md
│        ├── Plugin.md
│        └── README-ja.md
```

**Comment by iamkun** [comment]
@ohbarye THX, `docs/ja/README-ja.md` would be nice. It's easy to manage I think.

**Comment by iamkun** [comment]
Cool

**Comment by ohbarye** [comment]
thanks for your review!

**Comment by iamkun** [comment]
@ohbarye 😁 we are cool

**Pull request merged**
