### PR TITLE
add zh locale

### PR DESCRIPTION
**Pull request by ZYinMD**
In `window.navigator.languages` in Chrome, there are 4 valid Chinese locales that could appear: `zh`, `zh-cn`, `zh-cn`, `zh-hk`. Currently `zh` is missing from dayjs. This PR adds the `zh` locale.

`zh` has some minor improvements over the other 3 locales. For developers, this won't affect your existing code, but if you start using `zh`, your output will be slightly more correct in some occasional cases.

For example:

```js
// no more unecessary whitespace:
dayjs().locale('zh-cn').subtract(7, 'month').fromNow() // 7 个月前
dayjs().locale('zh').subtract(7, 'month').fromNow() // 7个月前

// use "后" instead of "内" for relative future:
dayjs().locale('zh-cn').add(3, 'day').fromNow() // 3 天内
dayjs().locale('zh').add(3, 'day').fromNow() // 3天后

// improve ordinal week of year:
dayjs('2020-10-13').locale('zh-tw').format('wo') // 42日 // wrong
dayjs('2020-10-13').locale('zh-hk').format('wo') // 42日 // wrong
dayjs('2020-10-13').locale('zh-cn').format('wo') // 42周 // ok
dayjs('2020-10-13').locale('zh').format('wo') // 第42周 // better
```
issue #820

### CODE REVIEW

**Comment by iamkun** [comment]
please add test

**Comment by ZYinMD** [comment]
Honestly I looked everywhere in the codebase and didn't find how it should be tested, and why existing tests are not passing... I compared with #516, which didn't add any tests either, and seems it did exactly the same thing as this one.

哭了

**Comment by iamkun** [comment]
test/locale/zh-cn.test.js

**Comment by iamkun** [comment]
I'll keep the same at this moment. And update it all together later.

**Pull request merged**
