### PR TITLE
Refactor regex

### PR DESCRIPTION
**Pull request by suspectpart**
@xxyuk @iamkun The regex refactoring. First commit just escapes the dot and removes the check for the trailing `'z'` /` 'Z'`, keeping tests green. The second commit shortens the regex, causing more strings to be run through the Date constructor. This should be verified against all Browsers in your CI build.

### CODE REVIEW

**Comment by xxyuk** [comment]
oops, `dayjs('2018-03-27')`  test faild on ios safari.

**Comment by suspectpart** [comment]
> oops, `dayjs('2018-03-27 11:49')` test faild on ios safari.

Is there any way to access the test report?

**Comment by xxyuk** [comment]
I tested on my phone manually.

**Comment by iamkun** [comment]
I'll close this pr since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
