### PR TITLE
implemented isBetween inclusivity

### PR DESCRIPTION
**Pull request by waseemahmad31**
This pull request will fix issue  #429 and #385

Implemented inclusivity option for isBetween function

### CODE REVIEW

**Comment by iamkun** [comment]
Seems good

**Comment by waseemahmad31** [comment]
@iamkun, let me know if any changes or action required from my side to merge this pull request.

**Comment by iamkun** [comment]
@waseemahmad31 Nope, all good :)

**Comment by coatesap** [comment]
Surely this is one part of Moment's API that really shouldn't have been adopted? The chances of developers correctly remembering what arbitrary characters mean without referring to the documentation seem close to zero!

**Comment by iamkun** [comment]
> Surely this is one part of Moment's API that really shouldn't have been adopted? The chances of developers correctly remembering what arbitrary characters mean without referring to the documentation seem close to zero!

This is releaded already.

**Comment by coatesap** [comment]
Yes, I'm aware that it's been released - I was just hoping to start a discussion about whether this was the right decision, and if not, whether we should propose a different API going forwards (obviously with deprecations or backwards compatibility breaks if it was in a new major version).

**Pull request merged**
