### PR TITLE
Fix error in relativeTime plugin when the interval is 1 second

### PR DESCRIPTION
**Pull request by jansons**
Fixes bug introduced in #558

### CODE REVIEW

**Comment by iamkun** [comment]
@jansons thanks, and what's this fix for?

**Comment by jansons** [comment]
@iamkun There was a runtime TypeError when the calculated interval is 1 second.
You can try to run updated tests on v1.8.13 to get the error

**Comment by iamkun** [comment]
Nice fix, thanks

**Comment by eamodio** [comment]
@iamkun will there be a new release with this fix soon?

**Comment by iamkun** [comment]
of course 😁

**Pull request merged**
