### PR TITLE
Add en-in and en-tt locales

### PR DESCRIPTION
**Pull request by ElliotAshby**
Addition of en-in and en-tt locales as extensions of the en-gb locale so that the correct date formats are used for these locales rather than using the default en formatting.

### CODE REVIEW

**Comment by iamkun** [comment]
Seems not quite necessary?

Why not just parse the locale string before passing into `dayjs.locale`?

**Comment by ElliotAshby** [comment]
Well, we support A LOT of locales (or at least try to), so it wouldn't really be reasonable to have to check each and every locale for what should be used in it's stead. We currently default to the base language's locale if the specific country's locale is not supported but I imagine for a lot of locales this is not correct. I figured it'd be a good thing for dayjs to support as many locales as possible out of the box, especially this way, as it is rather lightweight.
A lot of the currently supported english locales I noticed are almost exactly the same, perhaps a similar approach could be adopted with those to make them more lightweight?

**Comment by iamkun** [comment]
Can you provide a list on Wikipedia or some alike that has these two locale strings, please?

Besides, please avoided using es6 syntax. Cause it will enlarge the final bundle size.

**Comment by ElliotAshby** [comment]
Not entirely sure what you mean but I looked here at these links when confirming what was required.
http://www.localeplanet.com/icu/en-IN/index.html & http://www.localeplanet.com/icu/en-TT/index.html
So you'd rather have the locales defined in full to reduce bundle size?

**Comment by iamkun** [comment]
> So you'd rather have the locales defined in full to reduce bundle size?

Yes, please. 

And any difference between en-IN and en-in, or which one we should choose?

**Comment by ElliotAshby** [comment]
I've dropped the ES6 syntax, although I saw no difference in build size locally.

As for en-IN vs. en-in, the capitalised country code is the standard as far as I'm aware. But the locales in dayjs use lowercase country codes (except en-SG, not sure why). Perhaps it would be good to make things consistent?

**Comment by iamkun** [comment]
Thanks, let's get this merged first. 😬

**Comment by ElliotAshby** [comment]
thanks

**Pull request merged**
