### PR TITLE
docs: improve set('d', 1) API introduction

### PR DESCRIPTION
**Pull request by jk2K**

### CODE REVIEW

**Comment by iamkun** [comment]
Any explanation, please?

**Comment by jk2K** [comment]
`set` API semantics are not clear enough, 

On sunday, I thought `set('d', 1)` would get the date of current week, and the result got the date of next week, so I think the documentation needs to be improved

**Comment by iamkun** [comment]
Yes. This is exactly the same behavior with javascript built-in `Date.setDay`.

**Comment by iamkun** [comment]
I'll close this pr since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
