### PR TITLE
minor update, correcting semantics

### PR DESCRIPTION
**Pull request by pete-arif**

### CODE REVIEW

**Comment by iamkun** [comment]
@pete-arif

Ref: https://github.com/moment/moment/blob/develop/locale/ms.js

**Comment by iamkun** [comment]
@pete-arif Any comments here?

**Comment by pete-arif** [comment]
it's to correcting semantics

**Comment by iamkun** [comment]
@pete-arif
But according to 
https://github.com/moment/moment/blob/develop/locale/ms.js

This should be the right version?

**Comment by pete-arif** [comment]
https://github.com/moment/moment/blob/develop/locale/ms.js is correct indeed. The one I am suggesting is more formally used. Perhaps need todo pull request on that one instead?

**Comment by iamkun** [comment]
@pete-arif 
As you could imagine, this is a hard desition to me cause I'm not a native speaker of your language.
That's why I use moment's locale as a reference. 

Maybe we need some more reviewers from your language to make updates of both locales altogether.

**Pull request closed without merging**
