### PR TITLE
add Japanese locale unit tests

### PR DESCRIPTION
**Pull request by zoshigayan**
There was no test for Japanese so I added that.
It based on [Finnish's one](https://github.com/iamkun/dayjs/blob/dev/test/locale/fi.test.js) 🙏

### CODE REVIEW

**Comment by zoshigayan** [comment]
Ahh zh test failed on `dev` ...
https://github.com/iamkun/dayjs/runs/1570863405

**Comment by iamkun** [comment]
thanks, we have just fixed the test in dev branch

**Comment by zoshigayan** [comment]
thank you! I've merged it: https://github.com/iamkun/dayjs/pull/1280/commits/7cb8e32455ae321a49e5c35a42a6e31ed36afb95

**Pull request merged**
