### PR TITLE
fix: Locale: bo [Tibetan]: corrected the orders in formats

### PR DESCRIPTION
**Pull request by KalDhondup**
Hi, dayjs is great. I have used it in my recent project. Thanks. But there is some formats which are incorrect in Tibetan. 
like, In Tibetan its, ལོ་ 6 (means 6 years) rather than 6 ལོ ( which sounds like years 6 in English ). 

Here are some correct formats that we are able to do. Thanks again! Cheers! :)

### CODE REVIEW

**Comment by iamkun** [comment]
LGTM. @KalDhondup would you please ask a native speaker to review this PR before it gets merged? Thanks

**Review by KalDhondup — COMMENTED** [review]
Fixes from a native Tibetan speaker

**Comment by KalDhondup** [comment]
Hi @iamkun, Thanks. We discussed with a native speaker and he did some more corrections. It's thoroughly reviewed.

**Comment by KalDhondup** [comment]
Hi @iamkun, since there is issue with this merge, we created a [new pull request](https://github.com/iamkun/dayjs/pull/1833)

**Comment by iamkun** [comment]
Hi, please fix the lint error before the PR get merged

```
/home/travis/build/iamkun/dayjs/src/locale/bo.js
  11:1  error  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by KalDhondup** [comment]
Hi @iamkun, The issue is fixed. Its good to go 👍

**Pull request merged**
