### PR TITLE
Improve relative time in Chinese locales

### PR DESCRIPTION
**Pull request by ZYinMD**
Two minor changes to the relative date part in the Chinese locales `zh-cn`, `zh-hk`, and `zh-tw`.

- fix spacing in relative time:
There should be no whitespace between numbers and units in Chinese. 
For instance, `3 days` is `3天`, not `3 天`.

- fix wording of "future" in relative time:
The correct word for "future" in Chinese is 后, not 内. 
For instance, `in 3 days` is `3天后`, not `3天内`.

### CODE REVIEW

**Comment by iamkun** [comment]
Hi, we keep the same with moment.js 

https://github.com/moment/moment/blob/develop/locale/zh-cn.js#L84

**Comment by ZYinMD** [comment]
I don't mind submitting a pull request to moment.js, but are they still being actively maintained and accepting new merges? It seems their last release was January 2019?

**Comment by iamkun** [comment]
@ZYinMD That would be nice. I will merge this as soon as that PR get merged.

**Comment by iamkun** [comment]
我也觉得我们的中文写法需要改一下会更地道，但是现在比较纠结的事情是还要不要和 moment 保持一致，如果不一致，和这个库一开始做的初衷又不一样了

**Comment by ZYinMD** [comment]
矮马, dayjs的作者大佬原来是同胞, 66666, 之前都没注意到~ 你觉得`in 2 months`翻译成`2个月内`真的合适嘛? 

我暂时去node_modules里面改源码来解决我自己的应用问题~ 你先继续纠结吧~ 对于这个PR的决定, 你绝对是全世界第一权威

moment肯定不如你权威, 如果是其他locale的PR也就算了, 这个关于zh的PR肯定是你最权威~ 况且moment已经凉了, 哈哈

**Comment by iamkun** [comment]
https://day.js.org/docs/en/plugin/update-locale 你可以用这个

**Comment by ZYinMD** [comment]
哦哦哦! 管用管用!! 谢谢!! 没好好看doc是我的锅

话说, 我又想到了一个政治正确的workaround, 等我去新开一个issue

**Comment by iamkun** [comment]
#822

**Pull request closed without merging**
