### PR TITLE
fix: Kurdish locale strings and formatted output contains non-standard kurdish characters

### PR DESCRIPTION
**Pull request by akamfoad**
1. move: arabic to english number maps into constants:
  **Arabic** numbers are common in many `RTL` languages, which makes sense for `Arabic`->`English and `English`->`Arabic` numbers mapping be factored out into a more general file so that other locales can import it and use it without the need to duplicate in the source code it.
2. fix: https://github.com/iamkun/dayjs/issues/1728
  - fix usage of non-standard Kurdish characters in ku locale
  - add preparse and postformat to ku locale so that the formatted dates will contain correct Arabic numbers that Kurdish language uses.
3. fix: month names to be more aligned towards Kurdish month names as explained in this [Wikipedia page](https://ckb.wikipedia.org/wiki/%DA%95%DB%86%DA%98%DA%98%D9%85%DB%8E%D8%B1%DB%8C_%D8%B2%D8%A7%DB%8C%DB%8C%D9%86%DB%8C)

### CODE REVIEW

**Review by mhmd-azeez — APPROVED** [review]
lgtm

**Comment by iamkun** [comment]
Thanks.

Would you please revert the change "move: arabic to english number maps into constants:"? 

I think it's better to put them inside each locale file.

**Comment by akamfoad** [comment]
@mhmd-azeez Thanks for the review, I really appreciate it.

**Comment by akamfoad** [comment]
@iamkun Of course, done!

**Comment by iamkun** [comment]
Cool

**Pull request merged**
