### PR TITLE
fix: wrong ordinal for fr local

### PR DESCRIPTION
**Pull request by R3tep**
This pull request fix a wrong ordinal definition for fr local.

### CODE REVIEW

**Comment by iamkun** [comment]
Is fr locale's ordinal different under different format token? 

ref https://github.com/moment/moment/blob/develop/src/locale/fr.js#L82

**Comment by iamkun** [comment]
Thanks, let's get this merged

**Comment by xavier-villelegier** [comment]
Hey @R3tep, why this change ? In french when it's the 1st of July for exemple we say "1er juillet 2022", but for the 2nd, we never write "2e juillet 2022" or "3e juillet 2022" ? What was your use case ?

cc @iamkun

**Comment by CBD-iBiZa** [comment]
> Hey @R3tep, why this change ? In french when it's the 1st of July for exemple we say "1er juillet 2022", but for the 2nd, we never write "2e juillet 2022" or "3e juillet 2022". This might be correct mathematically speaking, but not in term of dates ? What was your use case ?
> 
> cc @iamkun

For week of year, with ordinal ([wo format](https://day.js.org/docs/en/plugin/advanced-format)), the output in french is not correct.
- 1st (week) => 1re (semaine), not 1er (semaine)
- 2nd (week) => 2e (semaine), not 2 (semaine)
- 3rd (week) => 3e (semaine), not 3 (semaine)
- ...

It was perfectly ok [in Moment](https://github.com/moment/moment/blob/develop/src/locale/fr.js#L98), not with DayJS+WeekOfYear plugin.

**Pull request merged**
