### PR TITLE
Consider using Intl api and update customParseFormat

### PR DESCRIPTION
**Pull request by iamkun**

### CODE REVIEW

**Comment by janat08** [comment]
So does this simply improve performance building on my code, and if so can I get a share of bounty for helping.

**Comment by iamkun** [comment]
@janat08 That would be nice.

This PR is only a test at the moment, still, I did not find a good way of implementing day time saving with timezone. e.g. dayjs('now', 'time-zone').add(1, 'month') , this might have a DTS rule change.

**Comment by janat08** [comment]
ermon.jas@gmail.com is my PayPal.

I don't remember, but presumably you're aware of a function for detecting dst changes (should output a diff in tz with dst in play) in my code.

**Comment by iamkun** [comment]
What I really mean is if we update DST in initialization only, that's not a quite right way to implement time zone. Cause this will cause errors after manipulation.

As a result, I may close the PR and look for another way to deal with DST after manipulation.

**Comment by janat08** [comment]
I think I thought the utc offset and target locale variable should be used along with dst check once output of dayjs date is required. if you require comp perf the old method should be used. It should be outlined in my PR.

**Comment by iamkun** [comment]
Besides, APIs like startOf, endOf will also cause a DST failure, if we only store a fixed offset like this PR. 

I guess, this might not the right way to implement tz.

**Comment by janat08** [comment]
Looking at my code again, I belief the proto.tz method is for correcting date after day boundary pass, I assume it will integrate with any API so long as it runs the tz function.

**Comment by janat08** [comment]
Did no other library like moment for example account for dst using browser API?

**Comment by janat08** [comment]
As for the startof method there would have to be trickery involved, which would be the reason why I didn't jump to integrating tz with dayjs apis.

I think integration would look like running tz method as very first thing, and etc.

**Comment by janat08** [comment]
I don't have a personal computer to help, nor a public one with quarantine, and so I would clearly appreciate a share of the bounty.

**Pull request closed without merging**
