### PR TITLE
feat: Added method to retrieve week of the year

### PR DESCRIPTION
**Pull request by naulacambra**
Added API method `week()` to retrieve week of the year

### CODE REVIEW

**Comment by iamkun** [comment]
@naulacambra Nice code, thanks. How about added this as a plugin `weekOfYear`?

**Comment by naulacambra** [comment]
Since moment.js has this method, and I personally think is quiet usefull, I've not thought adding it as a plugin.

Right now, the package has all `get` methods, but `week`, and it kinda feels right to add it here.

What we could win adding it as a plugin?

**Comment by iamkun** [comment]
The reason why I'm not adding this to the core code at the first beginning is because it's not that widely used compared to other APIs.

However, as a useful API, we should add to our lib. That's why I think a plugin might be a better choice.

**Comment by iamkun** [comment]
@naulacambra No problem 😁

**Comment by naulacambra** [comment]
Moved code from core to weekOfYear plugin

**Comment by naulacambra** [comment]
Updated Plugin.md doc file (english version)

**Pull request merged**
