### PR TITLE
Italian locale relative time translation fix

### PR DESCRIPTION
**Pull request by guidolodetti**
"3 hours ago"

Currently it is translated to "da 3 ore". It is grammatically correct, but it has a different meaning (it means that something has been occurring for 3 hours, not that occurred 3 hours ago).

The correct translation would be "3 ore fa". MomentJS translates it in the same way.

### CODE REVIEW

**Comment by iamkun** [comment]
Looks good! Can you cherry-pick and submit your commit only, please?

**Comment by guidolodetti** [comment]
Hi @iamkun! Can you please suggest me how to do it? I have never done it before. Thanks!

**Comment by iamkun** [comment]
@guidolodetti  You can try `merge origin/dev` first.

**Pull request merged**
