### PR TITLE
Add Bengali (bn) support for numerals

### PR DESCRIPTION
**Pull request by danielwinkler**
Following the work that has been done for AR numerals, this PR is about to add BN numeral.]

(It also fixes an inconsistency of the months with momentjs.)

### CODE REVIEW

**Comment by iamkun** [comment]
THX

**Comment by danielwinkler** [comment]
you're welcome!
(would be nice if you could release a patch version already)

**Comment by danielwinkler** [comment]
@iamkun would it be possible to release a new version please?

**Comment by iamkun** [comment]
sure, it's time

**Comment by danielwinkler** [comment]
Thanks!

**Pull request merged**
