### PR TITLE
fix: Update missing calendar for VI

### PR DESCRIPTION
**Pull request by giautm**
Copied from momentjs: https://github.com/moment/moment/blob/2c0b063b3bf95a285f9b38c173e262b6416c2e7f/locale/vi.js#L52-L59

### CODE REVIEW

**Comment by iamkun** [comment]
Hi, would you please fix this lint issue?
Thanks
```
/home/travis/build/iamkun/dayjs/src/locale/vi.js
  46:18  error  Unexpected trailing comma  comma-dangle
```

**Comment by giautm** [comment]
@iamkun Hi, I fixed it.

**Comment by iamkun** [comment]
My bad, I did not check it clearly. 

At present, we plan not to add calendar property to the locale file.

**Comment by giautm** [comment]
Hi @iamkun , If it was deprecated, how I can solve problem with calendar format? What's alternative API?

**Comment by iamkun** [comment]
You can also pass specifying calendar output formats as the second parameter.

ref: https://day.js.org/docs/en/display/calendar-time

**Comment by giautm** [comment]
Thank you, But I'm not directly use DayJS in our code. I use  [GetStream/stream-chat-react-native](https://github.com/GetStream/stream-chat-react-native), [GetStream/stream-chat-react](https://github.com/GetStream/stream-chat-react) to implement the Chat feature and they use DayJS to format calendar time.

I will use [`updateLocale`](https://github.com/GetStream/stream-chat-react/blob/1c8f0f996a3ed121f523af551df5fe9fb180f580/src/i18n/Streami18n.js#L46-L55) instead change their code.

**Pull request closed without merging**
