### PR TITLE
fix: correct past property in KU (kurdish) locale

### PR DESCRIPTION
**Pull request by mahamaad**
hello dayjs, in this pr add value to past property in english say ago say in kurdish say something like لەمەوپێش 

thank you.

### CODE REVIEW

**Comment by iamkun** [comment]
Should we keep the same with moment.js translation? https://github.com/moment/moment/blob/develop/src/locale/ku.js#L86

**Comment by mahamaad** [comment]
We need to change it in moment.js too

**Comment by iamkun** [comment]
alright, thanks. Could you ask another native speaker to review this PR before it gets merged?

**Comment by mahamaad** [comment]
Sure

**Comment by mahamaad** [comment]
@hariiad @roj1512, Please can you review it?

**Comment by roj1512** [comment]
There is a serious problem.

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by CYAXXX** [comment]
Ku isn't for Sorani guys, Come on!

**Comment by roj1512** [comment]
@CYAXXX I'll make a PR to fix that after this is merged. This is just a typo fix.

**Comment by iamkun** [comment]
@mahamaad I did not really get your conversation. Is this PR a correct fix on ku.js, or should we move it to another file?

**Comment by mahamaad** [comment]
> @mahamaad I did not really get your conversation. Is this PR a correct fix on ku.js, or should we move it to another file?

Yeah this pr correct fix past property u can approve it, 
but in fact, because Kurdish have two dialects, Sorani and Kurmanji, which have the most speakers, we need to rename the file from ku to Kurdish Sorani. We can rename it in this pr or make another pr which do you prefer?

**Comment by roj1512** [comment]
@iamkun Here's it:

- You just merge this and done.

We'll take care of the rest.

**Comment by iamkun** [comment]
Cool, I'll merge this first.

**Pull request merged**
