### PR TITLE
Fix 'ru' locale

### PR DESCRIPTION
**Pull request by CreativeRusBear**
- **'ru'** folder has been renamed on **'ru-ru'** (based on description on the [LocalePlanet](http://www.localeplanet.com/icu/ru-RU/index.html) website);
- A grammatical error has been fixed in the **README-ru.md** file;
- Some phrases have been rewrote (for easier reading);
- Missed word **'parse'** has been translated.

### CODE REVIEW

**Comment by iamkun** [comment]
Thanks for the gramma correction.

However, it is better to leave the folder name the same as before. Otherwise, this may cause a 404 to external links.

**Comment by CreativeRusBear** [comment]
@iamkun Done

**Comment by iamkun** [comment]
Cool thanks

**Pull request merged**
