### PR TITLE
fix german locale

### PR DESCRIPTION
**Pull request by borgiman**

### CODE REVIEW

**Comment by iamkun** [comment]
@borgiman  thanks, what's this fix for ?

**Comment by borgiman** [comment]
@iamkun The old translation was not correct. I'm not sure how to say this in english. The words were not wrong, but if you combine future or past value with another one then it changes how you say it.

**Comment by saviomuc** [comment]
As a native German speaker I fully support this PR. In my project I had to rewrite the config for relativeTime to achieve the same:

```
const germanLocale = Object.assign({}, de, {
  relativeTime: {
    future: 'in %s',
    past: 'vor %s',
    s: 'wenigen Sekunden',
    m: 'einer Minute',
    mm: '%d Minuten',
    h: 'einer Stunde',
    hh: '%d Stunden',
    d: 'einem Tag',
    dd: '%d Tagen',
    M: 'einem Monat',
    MM: '%d Monaten',
    y: 'einem Jahr',
    yy: '%d Jahren',
  },
});
```

**Comment by iamkun** [comment]
thanks @saviomuc @borgiman, will merge to next release. cheers.

**Pull request merged**
