### PR TITLE
translated readme.md file on Russian language

### PR DESCRIPTION
**Pull request by CreativeRusBear**

### CODE REVIEW

**Comment by iamkun** [comment]
Cool, thanks.

**Comment by iamkun** [comment]
And wondering if you have the interest to help us translate our doc website. https://github.com/dayjs/dayjs-website/issues/5

PS: it's surely a LOT of work to do.

**Comment by CreativeRusBear** [comment]
@iamkun, why not?  I'm ready to help with it at free time😉

**Comment by iamkun** [comment]
@CreativeRusBear Awesome! feel free to reply to this issue https://github.com/dayjs/dayjs-website/issues/5 when you have time. I'll invite you to our Crowdin translation group.

**Pull request merged**
