### PR TITLE
Added Norwegian Bokmål "nb" locale.

### PR DESCRIPTION
**Pull request by cowai**

### CODE REVIEW

**Comment by iamkun** [comment]
@cowai  thanks cool

**Comment by cowai** [comment]
@iamkun Wow that was fast!
Looking forward for this to be available in a release.

**Comment by iamkun** [comment]
@cowai Will be available in next release.

Plus, according to other libs, weekdaysShort in Norwegian "nb" locale is not the first three letters.  Any update here?

**Comment by cowai** [comment]
@iamkun Thanks.
Both first 2 and 3 works in Norwegian.
I wondered what I should take but ended up doing the same as Swedish and Danish (90% same language) is in this project: https://github.com/iamkun/dayjs/blob/master/src/locale/da.js and  https://github.com/iamkun/dayjs/blob/master/src/locale/sv.js

**Comment by cowai** [comment]
@iamkun Oh, I misunderstood you at first.
Yes, all weekdays in Norwegian can absolutely be cut to use only first 2 and 3 letters.

**Comment by iamkun** [comment]
@cowai It's up to you, native speaker 😬.

**Pull request merged**
