### PR TITLE
Add sr and sr-cyrl locales

### PR DESCRIPTION
**Pull request by limonte**
There are 2 official alphabets for Serbian language - latin and cyrilic.

Naming is chosen to be the same as in moment.js

### CODE REVIEW

**Comment by iamkun** [comment]
THX, @limonte

**Comment by limonte** [comment]
Thanks for reviewing @iamkun! Can't wait toswitch from `moment` to `dayjs` in my project, will be able to do that right after this change will be released 🎉

**Comment by iamkun** [comment]
@limonte cheers.

**Pull request merged**
