### PR TITLE
immutable locale, docs update

### PR DESCRIPTION
**Pull request by iamkun**

### CODE REVIEW

**Comment by iamkun** [comment]
Hi, @ohbarye @ludvon 

In order to keep the same behavior with other APIs, I've changed `dayjs().locale` to a immutable action.

And also updated one line of the English doc like this:

```md
Changing locales locally
- Returns a new Dayjs object by switching to new locale.
```

For less confusion, would you please update your Docs if you have some free time? 

Cheers.

**Comment by ludvon** [comment]
@iamkun Great! The wording in my translation already implied it was immutable, so I don't need to change it.

**Comment by iamkun** [comment]
@ludvon great!

**Pull request merged**
