### PR TITLE
update: prevent rewriting and reduce bytes

### PR DESCRIPTION
**Pull request by a13821190779**

### CODE REVIEW

**Comment by Imperat** [comment]
Sorry, I forget about this:
https://babeljs.io/docs/plugins/transform-undefined-to-void/
Probably it's better to add this plugin to our babelrc config instead writing "eslint"-wrong code?

**Comment by Imperat** [comment]
Not sure about right solution - we use "undefined" word only in this one line and it seems ugly to add separate babel plugin only for modify just one line..

**Comment by iamkun** [comment]
> seems ugly to add separate babel plugin only for modify just one line..
Nice plugin, but maybe just do it manually this time.

**Comment by a13821190779** [comment]
Haven't merged yet?

**Comment by guisturdy** [comment]
as i said in #185 , `rollup-plugin-uglify` plugin we used in `build/rollup.config.js` is already help us do this, change code here would not saving any byte.

**Comment by iamkun** [comment]
🎉 This PR is included in version 1.6.4 🎉@a13821190779

**Pull request merged**
