### PR TITLE
පරිවර්තන නිවරදි කිරීම

### PR DESCRIPTION
**Pull request by Aikatsui**
This fix incorrect localization for sinhalese/sinhala language (sri lanka). Below describe using examples

e.g. January
current: ජනවාරි (janavaari)
update: දුරුතු (duruthu)

e.g. August
current: අගෝස්තු (agoosthu)
update: නිකිණි (nikini)

I saw @aadityataparia @iamkun have updated `si.js` then do you remember the source of that resources? if then it will helpful for me to follow and re-correct.

### CODE REVIEW

**Comment by iamkun** [comment]
the source file should be this https://github.com/moment/moment/blob/develop/locale/si.js

**Comment by Aikatsui** [comment]
> the source file should be this https://github.com/moment/moment/blob/develop/locale/si.js

謝謝! I already found it and added PR. you can merge this changes meanwhile however let me know if i need to provide more details about that

**Comment by Aikatsui** [comment]
@iamkun can you add this language to https://crowdin.com/project/dayjs

**Comment by iamkun** [comment]
I'm not sure if we should keep the same with momentjs or not?

**Comment by Aikatsui** [comment]
> I'm not sure if we should keep the same with momentjs or not?

Same PR for that repository https://github.com/moment/moment/pull/5877
There're many localization related fixes PRs on momentjs [moment/pulls](https://github.com/moment/moment/pulls) but it seems take long time for review them

>Project Status
Moment.js is a legacy project, now in maintenance mode. In most cases, you should choose a different library.

>https://momentjs.com/docs/#/-project-status/
> - We will not be making any major changes (no version 3).
> - We may choose to not fix bugs or behavioral quirks, especially if they are long-standing known issues.

May be, someone from dayjs able to join to momentjs for review PRs for example. I'm not sure if that necessary or convenient otherwise you may able to take a look at important PRs randomly and apply them to dayjs.

**Comment by iamkun** [comment]
Thanks, I'll mark this PR for more code review by native speakers before it gets merged.

**Comment by dinithija** [comment]
@iamkun @Aikatsui notified me; I'm sinhalese language native speaker.

- About the PR - it's correct. people're using them since ancient times and now, also for astrology, horoscopes etc.
  - https://si.wikipedia.org/wiki/චන්ද්‍ර_මාස
- About old names - those're westernized/adopted words for unknown purposes some years ago. eg: follow western style. 
 (above @Aikatsui has provided examples; eg: january - ජනවාරි (janavaari)

**Comment by itsnotsaved** [comment]
> Thanks, I'll mark this PR for more code review by native speakers before it gets merged.

can you merge this? that is perfect; will remove current loan words.

**Comment by iamkun** [comment]
sure, LGTM

**Pull request merged**
