### PR TITLE
Add relative locales to czech language

### PR DESCRIPTION
**Pull request by NikolaRusakov**
Add czech language locale fuctionality

### CODE REVIEW

**Comment by prantlf** [comment]
Coincidentally, I [added the Czech locale](https://github.com/prantlf/dayjs/blob/czech-locale/src/locale/cs.js) too :-) As a part of PR #305 with the plugin called [LocalisableFormat].

Differences to this PR:

* The key "s" translated as "several seconds" and not "second".
* Keys for the single value (s, m, h, d, M, Y) translated with the correct declension:
  - if used in the expression for the future.
  - if used in the expression with duration; only if the duration is used in accusative - in the expression "takes ..."., for example 

In my case, expressions for the past cannot be translated correctly,because the preposition needs a different declension. In your case, you decided to translate correctly expressions of the past (although moving the preposition "before" after the value feels weird) and durations in nominative.

I opened issue #302 to explain and discuss the problem of the correct localisation. I sent PR #304, which localises the three scenarios (duration, future and past) with three different texts, if needed in a particular locale. I [updated the Czech locale](https://github.com/prantlf/dayjs/blob/fusional-languages/src/locale/cs.js) in this PR accordingly.

[LocalisableFormat]: https://github.com/prantlf/dayjs/blob/localisable-formats/docs/en/Plugin.md#localisableformat

**Comment by greegus** [comment]
@NikolaRusakov beware that the weekdays list should be indexed from Sunday, not Monday.
https://github.com/iamkun/dayjs/blob/master/src/locale/de.js

**Comment by stepanh** [comment]
Czech language requires more complex rules as highlighted by @prantlf above

**Comment by iamkun** [comment]
I'll merge #461 first, cause weekdays list should be indexed from Sunday.

BTW, @stepanh I'll do it later to support more complex rules like prantlf mentioned above.

**Comment by stepanh** [comment]
cc @prantlf

**Pull request closed without merging**
