### PR TITLE
[feature] Add parse duration from string

### PR DESCRIPTION
**Pull request by jamalroger**
Hello everyone,
This is a new feature can be adding to  moment duration
now we can create duration just from a string like  "1 day 57 minutes 34 seconds" will be  parse into normal object and create duration object
how work??
```js
console.log(dayjs.duration().fromString("1 day 57 minutes 34 seconds" )) // duration object
```

### CODE REVIEW

**Comment by iamkun** [comment]
why not passing an object instead?

**Comment by jamalroger** [comment]
I worked in project where the back-end return response  duration  like 1' day 57 minutes 34 seconds'
and  we want to parse it into  dayjs.duration to make some calculation 
For that reason I want this feature to be add  to dayjs

**Comment by iamkun** [comment]
I think this might not be the best way.

```
dayjs.duration({
  seconds: 34,
  minutes: 57,
  days: 1,
});
```

This should be enough? All you need is a custom converter to do this.
```
1' day 57 minutes 34 seconds' ->  {
  seconds: 34,
  minutes: 57,
  days: 1,
}
```

**Comment by jamalroger** [comment]
I already do that, I want to be function in dayjs but if not the best way I will close the pull request

**Pull request closed without merging**
