### PR TITLE
fix: update zh-tw, zh-hk locale files with correct week start

### PR DESCRIPTION
**Pull request by LeoLiu1209**
update missing week start in locale/zh-tw, zh-hk

### CODE REVIEW

**Comment by iamkun** [comment]
Checked`locale/zh-tw`, `locale/zh-hk` in momentjs, no this config. 😢

**Comment by LeoLiu1209** [comment]
Sorry I didn’t notice that momentjs doesn’t include the config for these two locale

BTW, the config u mention is something like this code down below
 
 week : {
            // GB/T 7408-1994《数据元和交换格式·信息交换·日期和时间表示法》与ISO 8601:1988等效
            dow : 1, // Monday is the first day of the week.
            doy : 4  // The week that contains Jan 4th is the first week of the year.
        }

If yes, maybe I could have a PR for it to momentjs once it is accepted, we could update the 
Week start in dayjs👍👍👍

**Comment by iamkun** [comment]
Yes, in momentjs `zh-cn` has this config, so do us. But the other two not.

Our lib is intend to keep the same behavior with momentjs, so it's better send a pr to them before this pr get merged.

**Comment by LeoLiu1209** [comment]
Ok thx a lot!!!
Once the PR is accepted by Momentjs, I will let u know👍👍👍👍

**Comment by iamkun** [comment]
I'll close this pr since it's been a while since it's been opened. Feel free to reopen if you have updates on  Momentjs side.

**Pull request closed without merging**
