### PR TITLE
Update de.js

### PR DESCRIPTION
**Pull request by PhilippMeissner**
[[This PR adds the abbreviations for German months including a `.` in the end, as in `September` -> `Sept.`.
[Duden DE](https://www.duden.de/rechtschreibung/Sept_)

### CODE REVIEW

**Comment by iamkun** [comment]
I'm not sure if this is a proper fix, seems we are the same with https://github.com/moment/moment/blob/develop/src/locale/de.js#L28

**Comment by PhilippMeissner** [comment]
> I'm not sure if this is a proper fix, seems we are the same with https://github.com/moment/moment/blob/develop/src/locale/de.js#L28

The abbreviation for `September` is different though. The proper abbreviation is `Sept.`, not `Sep`.

**Comment by iamkun** [comment]
Thanks

**Pull request merged**
